<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_lhNIKGIo</name>
   <tag></tag>
   <elementGuidId>85c1c96a-2dfe-42c1-9043-b2c12755ac83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='lhNIKGIo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lhNIKGIo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>8c29d164-b567-45d7-a8b3-9362537d82e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lhNIKGIo</value>
      <webElementGuid>6c999f84-efa9-4175-8376-4f0f08e88f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>424</value>
      <webElementGuid>de1a6fed-c25f-4160-b08c-263ff74a1a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>397</value>
      <webElementGuid>92265650-8750-432e-ae40-3c08b9bbebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lhNIKGIo&quot;)</value>
      <webElementGuid>d173f3b4-55fa-4fdd-8127-0a6f74945548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='lhNIKGIo']</value>
      <webElementGuid>ecf6fe5e-7263-4a10-a993-0c29de2a2239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>667f8b20-2dc3-4896-bc1a-77e3311589d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>b0f3a031-93a6-4662-8eea-1e8f67745342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'lhNIKGIo']</value>
      <webElementGuid>71825616-d0ea-410d-9284-d35034971efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
